
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.ssh.insert_key = false

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "main.yml"
  end

end
