version: "2.2"
services:
  web:
      # replace username/repo:tag with your name and image details
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:80"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - webnet
networks:
  webnet: