
Vagrant.configure("2") do |config|

  config.vm.box = "ancient/Centos7.Ansible"
  config.ssh.insert_key = false

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "docker-install.yml"
  end
  
end
