- name: Install MongoDB
  hosts: all
  become: true

  vars:
    main_user: vagrant
    python_version_major: 3.6
    python_version_minor: 1
    python_env: mongosandbox

  tasks:
    - include: mongo_install.yml
    - include: python_install.yml