- name: Install Flask
  hosts: all
  become: true

  vars:
    main_user: vagrant
    python_version_major: 3.6
    python_version_minor: 1
    python_env: flasksandbox

  tasks:
    - include: python_install.yml

    - name: Disable firewalld service
      service:
        name: firewalld
        state: stopped
        enabled: no